### ISSUE TITLE
rf_ files viewing problem

### ISSUE THREAD

**Issue by silverweihit** [David-Murray/REFIT#1]
Hi, I was trying to view the rf_ files using the phpnow-1.5.6, but failed and got this message.
"Fatal error: Class 'mysqli' not found in E:\PHPnow\htdocs\rf_list.php on line 34"
"Fatal error: Class 'mysqli' not found in E:\PHPnow\htdocs\rf_graph.php on line 21"
"Fatal error: Class 'mysqli' not found in E:\PHPnow\htdocs\rf_status.php on line 27"

seems Class 'mysqli' is missing? How can I fix it? Thank you

**Comment by David-Murray** [comment]
Make sure you have mysqli installed with your PHP installation. That should solve the issue, what operating system are you using?

**Comment by silverweihit** [comment]
It turns out to be the php configuration problem.  and I changed the "extension=php_mysqli.dll" expression.
However, here comes another error,  
"
Warning: mysqli::mysqli() [mysqli.mysqli]: (HY000/2005): Unknown MySQL server host 'xxxx' (11001) in D:\PHPnow\htdocs\rf_graph.php on line 21
Connection Failed: Unknown MySQL server host 'xxxx' (11001)
"

In the original rf_graph file, line 15 to line 21 are:
`<?php`
`$servername = "xxxx";`
`$username = "xxxx";`
`$password = "xxxx";`
`$dbname = "xxxx";`
`$conn = new mysqli($servername, $username, $password, $dbname);`
Should I replace "xxxx" with specific contents?

**Comment by silverweihit** [comment]
And I using in a Win10 system.

**Comment by David-Murray** [comment]
You'll need to set up a MySQL server on your machine and use the database schema from the REFIT-MYSQL.sql file to create the empty database structure.
All of the variables with "xxxx" will be specific to the MySQL server you set up.

**Comment by silverweihit** [comment]
Thanks a lot. It is my first time using PHP and SQL.
I have created the database 'refit' and sourced the REFIT-MYSQL.sql to 'D:/PHPnow/Mysql/data/refit';
changed 'xxxx’ to the following setting
`$servername = "localhost";
$username = "root";
$password = "123456";
$dbname = "refit";`
However, when I open rf_ files using "http://127.0.0.1/rf_graph.php", I got this information:

-  for rf_graph
Notice: Undefined index: houseID in D:\PHPnow\htdocs\rf_graph.php on line 53
Notice: Undefined variable: data_Set in D:\PHPnow\htdocs\rf_graph.php on line 36
Notice: Undefined variable: data_Set_Label in D:\PHPnow\htdocs\rf_graph.php on line 50
Check Sensors Check Scripts
Power 
Notice: Undefined index: houseID in D:\PHPnow\htdocs\rf_graph.php on line 105
Nothing Selected	, Aggregate

-  for rf_list
0 results (It's all gone wrong)

-  for rf_status
0 results (It's all gone wrong)

**Comment by David-Murray** [comment]
You haven't populated the database with values hence the nothing selected issue, this repository is to give an idea of how the REFIT dataset was created. It's not the way to access the data, the data is available at https://pureportal.strath.ac.uk/en/datasets/refit-electrical-load-measurements-cleaned
